---
- name: Add Java Repo
  apt_repository: repo='deb http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main'
                  state=present

- name: Add Java Repo APT key
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=EEA14886

- name: Accept Java License
  debconf: name='oracle-java8-installer'
           question='shared/accepted-oracle-license-v1-1'
           value='true'
           vtype='select'

- name: Install Java
  apt: name=oracle-java8-installer state=latest force=yes
